apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-cm

data:
  DATABASE: "db"
  USER: "wp"
  PASSWORD: "123"
  ROOT_PASSWORD: "123"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maria-dep
  name: maria-dep

spec:
  replica: 1
  selector:
    matchLabels:
      app: maria-dep
  template:
    metadata:
      labels:
        app: maria-dep
    spec:
      containers:
        image: test
        envFrom:
          - prefix: "MARIADB_"
        configMapRef: name:maria-cm
